// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from dto.proto

package com.poi.dto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class ProximityRequest implements Externalizable, Message<ProximityRequest>
{

    public static Schema<ProximityRequest> getSchema()
    {
        return SCHEMA;
    }

    public static ProximityRequest getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ProximityRequest DEFAULT_INSTANCE = new ProximityRequest();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Double latitude;
    Double longitude;

    public ProximityRequest()
    {
        
    }

    public ProximityRequest(
        Double latitude,
        Double longitude
    )
    {
        this.latitude = latitude;
        this.longitude = longitude;
    }

    // getters and setters

    // latitude

    public Double getLatitude()
    {
        return latitude;
    }

    public ProximityRequest setLatitude(Double latitude)
    {
        this.latitude = latitude;
        return this;
    }

    // longitude

    public Double getLongitude()
    {
        return longitude;
    }

    public ProximityRequest setLongitude(Double longitude)
    {
        this.longitude = longitude;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<ProximityRequest> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<ProximityRequest> SCHEMA = new Schema<ProximityRequest>()
    {
        // schema methods

        public ProximityRequest newMessage()
        {
            return new ProximityRequest();
        }

        public Class<ProximityRequest> typeClass()
        {
            return ProximityRequest.class;
        }

        public String messageName()
        {
            return ProximityRequest.class.getSimpleName();
        }

        public String messageFullName()
        {
            return ProximityRequest.class.getName();
        }

        public boolean isInitialized(ProximityRequest message)
        {
            return 
                message.latitude != null 
                && message.longitude != null;
        }

        public void mergeFrom(Input input, ProximityRequest message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.latitude = input.readDouble();
                        break;
                    case 2:
                        message.longitude = input.readDouble();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, ProximityRequest message) throws IOException
        {
            if(message.latitude == null)
                throw new UninitializedMessageException(message);
            output.writeDouble(1, message.latitude, false);

            if(message.longitude == null)
                throw new UninitializedMessageException(message);
            output.writeDouble(2, message.longitude, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "latitude";
                case 2: return "longitude";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("latitude", 1);
            fieldMap.put("longitude", 2);
        }
    };
    
}
